uniqueidmysql:
  image: mysql
  container_name: uniqueidmysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: pacifica_uniqueid
    MYSQL_USER: uniqueid
    MYSQL_PASSWORD: uniqueid

uniqueid:
  container_name: uniqueid
  build: .
  dockerfile: Dockerfile
  links:
    - uniqueidmysql:mysql
